# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-CVSMonitor
version:      1.01
version_from: lib/Bundle/CVSMonitor.pm
installdirs:  site
requires:
    Array::Window:                 0
    CGI:                           0
    CGI::Carp:                     0
    Chart::Math::Axis:             0.2
    Class::Autouse:                1
    Class::Default:                0.2
    Class::Handle:                 0
    Class::Inspector:              0.2
    Clone:                         0.13
    Config::Tiny:                  1.1
    Cwd:                           0
    File::Copy:                    0
    File::Find::Rule:              0
    File::Flat:                    0.8
    File::NCopy:                   0.32
    File::Remove:                  0.2
    File::Spec:                    0.82
    File::Temp:                    0.12
    FindBin:                       0
    GD:                            0
    GD::Graph:                     0
    GD::Text:                      0
    Getopt::Long:                  0
    HTTP::BrowserDetect:           0.97
    IO::File:                      0
    Net::Telnet:                   0
    Number::Compare:               0
    Proc::ProcessTable:            0
    Sort::Versions:                1.4
    Storable:                      0
    Text::Glob:                    0
    Time::Duration:                0
    Time::ParseDate:               100.010301
    URI::Escape:                   0
    Validate::Net:                 0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
